### ISSUE TITLE
key error when no year in imdb

### ISSUE THREAD

**Issue by manolismel** [manolismel/cinephile#3]
```
[2021-03-27 19:35:43,066] INFO:: first result for Treme Complete :  -> Let Me Complete You (in development) : https://www.imdb.com/title/tt12376098/ 
[2021-03-27 19:35:45,761] INFO:: I decided to keep the first result :)
Traceback (most recent call last):
  File "C:\Users\manolism\PycharmProjects\untitled\main.py", line 84, in <module>
    else:
  File "C:\Users\manolism\AppData\Local\Programs\Python\Python39\lib\site-packages\imdb\utils.py", line 1503, in __getitem__
    rawData = self.data[key]
KeyError: 'year'
```

**Comment by manolismel** [comment]
fixed
